#!/usr/bin/expect -f
#exp_internal 1
# Author: Abbas Moghtanei
# This expect script downlaods any file from hills to my machine.
#
if { $argc == 0 } \
{
   puts stderr "usage: $argv0 filename"
   exit 1
}
set timeout 20
set file [lindex $argv 0]
spawn bash -c "scp your-loginid\@147.144.1.2:$file ."
expect "*?assword:*"
send -- "your-password\r"
send -- "\r"
expect eof

