#!/usr/bin/expect -f
#exp_internal 1
# Author: Abbas Moghtanei
# This expect script send any file to hills.
#
if { $argc == 0 } \
{
   puts stderr "usage: $argv0 filename"
   exit 1
}
set timeout 20
set file [lindex $argv 0]
set dir  [lindex $argv 1]
spawn bash -c "scp $file your-loginid\@147.144.1.2:$dir"
expect "*?assword:*"
send -- "your-password\r"
send -- "\r"
expect eof

